package Entity;

import javax.persistence.*;
import java.util.Date;

@Table(name = "MEMBER", indexes = @Index(name = "name_idx1", columnList = "name"))
@Entity
public class Member {

    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)         // IDENTITY 로 줄 시 테이블 create query 에 "generated by default as identity" 라고 붙음

    // 이렇게 하면 한 번에 100 개 메모리에 올려놓고 사용하고 다 쓰면 다시 메모리에 올려놓고 하는 식이라고 함. 성능 최적화 할 수 있다고 함.
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_MEMBER")
    @SequenceGenerator(name = "SEQ_MEMBER", sequenceName = "SEQ_MEMBER", allocationSize = 100)
    private Long id;
    private int age;
    private String name;

    @Temporal(TemporalType.TIMESTAMP)
    private Date createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}
