-- 영화 추가
INSERT INTO MOVIE VALUES ('13', '장호', '130', '19');

-- 간식 추가
INSERT INTO SNACK VALUES ('13', '짜장', '9000');

-- 간식 변경
UPDATE SNACK SET SNACKNAME = '짬뽕', SNACKPRICE='5000' where SNACKNAME = '짬뽕';

-- 간식 삭제
DELETE FROM SNACK WHERE SNACKNAME='짬뽕';

-- 티켓 예매
INSERT INTO ticket VALUES (19, 'A', 3, 2, 2000);

-- 예약 삽입
INSERT INTO reservation VALUES (19, 19, 5);

-- userId 로 userIndex 구하기
SELECT USERINDEX FROM REGISTER WHERE ID = 'produce101';

-- 리뷰 추가
INSERT INTO REVIEW VALUES (13, 'produce101', 4, 5, '스레기');

-- 리뷰 수정
UPDATE REVIEW SET MOVIEINDEX = 1, STAR = 5, CONTENT = 'ㅎㅇ' WHERE CONTENT = '멋진 영화';

-- 굿즈와 스낵 테이블에서 3000 원 이상인 것 출력
SELECT DISTINCT GOODS.GOODSNAME, SNACK.SNACKNAME FROM GOODS, SNACK WHERE GOODS.GOODSNAME IN (SELECT GOODS.GOODSNAME FROM GOODS WHERE GOODS.GOODSPRICE > 3000) AND (SNACK.SNACKPRICE > 3000);

-- 스낵 테이블 가격 낮은 순으로
SELECT SNACKNAME, SNACKPRICE FROM SNACK ORDER BY SNACKPRICE ASC;